// Michigan Trout Report — Comprehensive Stream Registry
// 40+ verified USGS active gauges covering the full state
// parameterCd: 00060 = discharge (cfs), 00010 = water temp (C), 00065 = gage height (ft)
//
// Regions: 'UP' | 'NLP' | 'WLP' | 'CLP'
// Species: array of 'brook' | 'brown' | 'rainbow' | 'steelhead'
// Type: 'freestone' | 'spring_creek' | 'tailwater' | 'UP_headwater'
// Tier: 1 = direct gauge + temp, 2 = direct gauge flow-only, 3 = estimated (no gauge)

export const RIVERS = [

  // ─────────────────────────────────────────────
  // UPPER PENINSULA
  // ─────────────────────────────────────────────

  {
    id: 'black-river-up',
    name: 'Black River (UP)',
    region: 'Western Upper Peninsula',
    regionCode: 'UP',
    notes: 'Wild and remote brook trout fishery near Bessemer. Flows through the Porcupine Mountains area with stunning waterfalls. One of Michigan\'s most scenic trout streams.',
    species: ['brook', 'brown'],
    type: 'freestone',
    tier: 1,
    access: 'Black River Harbor Recreation Area, multiple county road access points',
    regulations: 'General trout regulations. Check DNR for special UP regulations.',
    primaryGauge: '04031000',
    gauges: [
      { id: '04031000', name: 'Black River near Bessemer' },
    ],
  },
  {
    id: 'presque-isle-river',
    name: 'Presque Isle River',
    region: 'Western Upper Peninsula',
    regionCode: 'UP',
    notes: 'Tumbles through dramatic gorges and waterfalls before emptying into Lake Superior. Excellent brook trout in the upper reaches. Part of Porcupine Mountains Wilderness.',
    species: ['brook', 'steelhead'],
    type: 'freestone',
    tier: 1,
    access: 'Porcupine Mountains State Park, US-2 bridges',
    regulations: 'General trout regulations. Lake Superior tributaries — check steelhead regs.',
    primaryGauge: '04032150',
    gauges: [
      { id: '04032150', name: 'Presque Isle River near Connorville' },
    ],
  },
  {
    id: 'sturgeon-river-up',
    name: 'Sturgeon River (UP)',
    region: 'Western Upper Peninsula',
    regionCode: 'UP',
    notes: 'One of Michigan\'s premier brook trout streams. Flows through the Ottawa National Forest — cold, clear, and remote. The native brook trout here are wild and beautiful.',
    species: ['brook'],
    type: 'UP_headwater',
    tier: 1,
    access: 'Ottawa National Forest roads, US-45 crossings',
    regulations: 'Special brook trout regulations apply — check DNR. Artificial lures only in sections.',
    primaryGauge: '04040500',
    gauges: [
      { id: '04040500', name: 'Sturgeon River near Sidnaw' },
      { id: '04041500', name: 'Sturgeon River near Alston' },
    ],
  },
  {
    id: 'ontonagon-river',
    name: 'Ontonagon River',
    region: 'Western Upper Peninsula',
    regionCode: 'UP',
    notes: 'Major UP river system with multiple branches. Steelhead and brown trout in lower sections; brook trout in the headwaters. Ottawa National Forest surrounds much of the river.',
    species: ['brook', 'brown', 'steelhead'],
    type: 'freestone',
    tier: 1,
    access: 'Rockland area, Ottawa NF access roads',
    regulations: 'General trout regulations. Lake Superior tributary — check steelhead season dates.',
    primaryGauge: '04040000',
    gauges: [
      { id: '04040000', name: 'Ontonagon River near Rockland' },
      { id: '04033000', name: 'Middle Branch near Paulding' },
      { id: '04036000', name: 'West Branch near Bergland' },
    ],
  },
  {
    id: 'trap-rock-river',
    name: 'Trap Rock River',
    region: 'Keweenaw Peninsula',
    regionCode: 'UP',
    notes: 'Remote Keweenaw Peninsula stream with wild brook trout. Native brook trout in cold headwaters. Lightly fished and extremely scenic. Spring steelhead run in lower river.',
    species: ['brook', 'steelhead'],
    type: 'UP_headwater',
    tier: 1,
    access: 'Keweenaw County roads — remote, minimal signage',
    regulations: 'General trout regulations.',
    primaryGauge: '04043050',
    gauges: [
      { id: '04043050', name: 'Trap Rock River near Lake Linden' },
    ],
  },
  {
    id: 'silver-river',
    name: 'Silver River',
    region: 'Baraga County, Upper Peninsula',
    regionCode: 'UP',
    notes: 'Small but productive brook trout stream in Baraga County. Classic UP headwater fishery — cold, clear, spring-fed. Often overlooked, rarely crowded.',
    species: ['brook'],
    type: 'UP_headwater',
    tier: 2,
    access: 'L\'Anse area county roads',
    regulations: 'General trout regulations.',
    primaryGauge: '04043150',
    gauges: [
      { id: '04043150', name: 'Silver River near L\'Anse' },
    ],
  },
  {
    id: 'salmon-trout-river',
    name: 'Salmon Trout River',
    region: 'Marquette County, Upper Peninsula',
    regionCode: 'UP',
    notes: 'Marquette County brook trout stream with wild native fish. Flows through Huron Mountains area — one of Michigan\'s most remote and least-accessible fisheries. Worth the effort.',
    species: ['brook'],
    type: 'UP_headwater',
    tier: 1,
    access: 'Big Bay area roads — remote, 4WD recommended',
    regulations: 'General trout regulations.',
    primaryGauge: '04043238',
    gauges: [
      { id: '04043238', name: 'Salmon Trout River near Big Bay' },
    ],
  },
  {
    id: 'au-train-river',
    name: 'Au Train River',
    region: 'Alger County, Upper Peninsula',
    regionCode: 'UP',
    notes: 'Flows through the Hiawatha National Forest into Au Train Lake and Lake Superior. Brook trout throughout; steelhead in spring. Beautiful forest setting near Pictured Rocks.',
    species: ['brook', 'steelhead'],
    type: 'freestone',
    tier: 1,
    access: 'Au Train, Hiawatha NF roads, M-28',
    regulations: 'General trout. Lake Superior tributary — steelhead season dates apply.',
    primaryGauge: '04044724',
    gauges: [
      { id: '04044724', name: 'Au Train River at Forest Lake' },
    ],
  },
  {
    id: 'miners-river',
    name: 'Miners River',
    region: 'Pictured Rocks, Upper Peninsula',
    regionCode: 'UP',
    notes: 'Flows through Pictured Rocks National Lakeshore. One of the most scenic trout streams in Michigan. Remote brook trout fishing with dramatic Lake Superior views nearby.',
    species: ['brook'],
    type: 'UP_headwater',
    tier: 2,
    access: 'Pictured Rocks NL — Miners Beach Road',
    regulations: 'National Lakeshore rules apply. Check NPS and DNR.',
    primaryGauge: '04044755',
    gauges: [
      { id: '04044755', name: 'Miners River near Munising' },
    ],
  },
  {
    id: 'tahquamenon-river',
    name: 'Tahquamenon River',
    region: 'Eastern Upper Peninsula',
    regionCode: 'UP',
    notes: 'One of the UP\'s great rivers. Famous for its tannin-stained falls. Brook trout in the upper watershed; steelhead enter the lower river. Tahquamenon Falls State Park surrounds much of it.',
    species: ['brook', 'steelhead', 'brown'],
    type: 'freestone',
    tier: 1,
    access: 'Tahquamenon Falls State Park, Paradise area',
    regulations: 'General trout. Lake Superior tributary — steelhead regs apply.',
    primaryGauge: '04045500',
    gauges: [
      { id: '04045500', name: 'Tahquamenon River near Paradise' },
    ],
  },
  {
    id: 'black-river-schoolcraft',
    name: 'Black River (Schoolcraft County)',
    region: 'Eastern Upper Peninsula',
    regionCode: 'UP',
    notes: 'Eastern UP brook trout stream in Schoolcraft County. Cold, tannin-stained waters produce wild native brookies. Remote and lightly fished — classic UP experience.',
    species: ['brook'],
    type: 'UP_headwater',
    tier: 2,
    access: 'Garnet area, Hiawatha National Forest roads',
    regulations: 'General trout regulations.',
    primaryGauge: '04046000',
    gauges: [
      { id: '04046000', name: 'Black River near Garnet' },
    ],
  },
  {
    id: 'paint-river',
    name: 'Paint River',
    region: 'Iron County, Upper Peninsula',
    regionCode: 'UP',
    notes: 'Central UP river system with wild brook trout. Flows through the Ottawa National Forest. Multiple forks converge in the Crystal Falls area. Good access and quality fishing.',
    species: ['brook', 'brown'],
    type: 'freestone',
    tier: 1,
    access: 'Crystal Falls area, Ottawa NF roads, M-69',
    regulations: 'General trout regulations.',
    primaryGauge: '04061500',
    gauges: [
      { id: '04061500', name: 'Paint River at Crystal Falls' },
      { id: '04062000', name: 'Paint River near Alpha' },
    ],
  },
  {
    id: 'iron-river',
    name: 'Iron River',
    region: 'Iron County, Upper Peninsula',
    regionCode: 'UP',
    notes: 'Iron County river with good brook trout fishing. Flows through the heart of the UP ironwood country. Accessible and underrated.',
    species: ['brook', 'brown'],
    type: 'freestone',
    tier: 1,
    access: 'Caspian, Iron River city access, US-2',
    regulations: 'General trout regulations.',
    primaryGauge: '04060500',
    gauges: [
      { id: '04060500', name: 'Iron River at Caspian' },
    ],
  },
  {
    id: 'michigamme-river',
    name: 'Michigamme River',
    region: 'Western Upper Peninsula',
    regionCode: 'UP',
    notes: 'Large UP river system below the Michigamme Reservoir. Good brown trout and steelhead in accessible sections. Flows through beautiful Ottawa National Forest terrain.',
    species: ['brown', 'brook', 'steelhead'],
    type: 'freestone',
    tier: 1,
    access: 'Crystal Falls area, Ottawa NF roads',
    regulations: 'General trout regulations.',
    primaryGauge: '04062500',
    gauges: [
      { id: '04062500', name: 'Michigamme River near Crystal Falls' },
    ],
  },
  {
    id: 'brule-river',
    name: 'Brule River (UP/Wisconsin Border)',
    region: 'Iron County, Upper Peninsula',
    regionCode: 'UP',
    notes: 'Forms the Michigan-Wisconsin state line. Excellent brook trout and brown trout. Both states require a valid license in their respective waters. Remote and often uncrowded.',
    species: ['brook', 'brown'],
    type: 'freestone',
    tier: 1,
    access: 'US-2 near Florence, WI — border river',
    regulations: 'Michigan or Wisconsin license required on respective side. Check both states\' regs.',
    primaryGauge: '04060993',
    gauges: [
      { id: '04060993', name: 'Brule River near Florence (border)' },
    ],
  },

  // ─────────────────────────────────────────────
  // NORTHERN LOWER PENINSULA
  // ─────────────────────────────────────────────

  {
    id: 'ausable',
    name: 'AuSable River',
    region: 'Northeast Lower Michigan',
    regionCode: 'NLP',
    notes: 'Holy Water stretch between Grayling and Mio. Premier wild trout fishery in the Midwest. Flies-only designated reaches, pristine spring-fed currents, legendary hatches. Home to Hex, Sulphur, and world-class rising brown trout.',
    species: ['brown', 'rainbow'],
    type: 'freestone',
    tier: 1,
    access: 'Grayling, Mio, Burton\'s Landing, Wakeley Bridge — extensive public access',
    regulations: 'Special regulations on Holy Water (flies-only, C&R). Check DNR for designated water rules.',
    primaryGauge: '04136500',
    gauges: [
      { id: '04135800', name: 'North Branch at Lovells' },
      { id: '04135700', name: 'South Branch near Luzerne' },
      { id: '04136000', name: 'Main Branch near Red Oak' },
      { id: '04136500', name: 'Main Branch at Mio' },
      { id: '04136900', name: 'Main Branch near McKinley' },
      { id: '04137005', name: 'Main Branch near Curtisville' },
      { id: '04137500', name: 'Main Branch near AuSable' },
      { id: '041377255', name: 'Main Branch near Oscoda' },
    ],
  },
  {
    id: 'manistee',
    name: 'Manistee River',
    region: 'Northwest Lower Michigan',
    regionCode: 'NLP',
    notes: 'Headwaters near Grayling, excellent brown trout in the upper reaches and world-class steelhead in lower sections. One of Michigan\'s longest and most diverse trout rivers.',
    species: ['brown', 'rainbow', 'steelhead'],
    type: 'freestone',
    tier: 1,
    access: 'Grayling (upper), CCC Bridge, High Bridge, Tippy Dam area',
    regulations: 'Various special regulations by section. Check DNR for current rules.',
    primaryGauge: '04123500',
    gauges: [
      { id: '04123500', name: 'Near Grayling (upper)' },
      { id: '04124000', name: 'Near Sherman (mid)' },
      { id: '04124200', name: 'Near Mesick' },
      { id: '04125550', name: 'Near Wellston (lower)' },
    ],
  },
  {
    id: 'pere-marquette',
    name: 'Pere Marquette River',
    region: 'West-Central Lower Michigan',
    regionCode: 'NLP',
    notes: 'Wild and Scenic designated. Premier steelhead and brown trout river. Gin-clear flows through Mason and Lake counties. One of the top 10 trout streams in North America.',
    species: ['brown', 'rainbow', 'steelhead'],
    type: 'freestone',
    tier: 1,
    access: 'Walhalla, Branch Bridge, Sulak, Scottville — state and national forest access',
    regulations: 'Flies-only designated section below Gleeson\'s Landing. Check DNR for full rules.',
    primaryGauge: '04122500',
    gauges: [
      { id: '04122500', name: 'At Scottville' },
    ],
  },
  {
    id: 'muskegon',
    name: 'Muskegon River',
    region: 'West-Central Lower Michigan',
    regionCode: 'NLP',
    notes: 'Tailwater fishery below Croton Dam. Year-round trout and steelhead thanks to cold, stable dam releases. One of the most productive and accessible trout rivers in Michigan.',
    species: ['brown', 'rainbow', 'steelhead'],
    type: 'tailwater',
    tier: 1,
    access: 'Croton Dam, Newaygo, Bridgeton — well-maintained public access sites',
    regulations: 'Catch-and-release season extended due to tailwater designation. Check DNR.',
    primaryGauge: '04121970',
    gauges: [
      { id: '04121500', name: 'At Evart (upper)' },
      { id: '04121650', name: 'At Big Rapids (mid-upper)' },
      { id: '04121970', name: 'Near Croton (tailwater)' },
      { id: '04122001', name: 'At Newaygo (lower)' },
    ],
  },
  {
    id: 'boardman',
    name: 'Boardman River',
    region: 'Northwest Lower Michigan',
    regionCode: 'NLP',
    notes: 'Flows through Traverse City. Quality wild brown trout fishery through Fife Lake and Boardman Valley. Underrated and often uncrowded compared to its famous neighbors.',
    species: ['brown', 'brook'],
    type: 'freestone',
    tier: 1,
    access: 'Brown Bridge Road, Scheck\'s Place, Boardman Valley Road',
    regulations: 'General trout. Check DNR for any designated special regulations sections.',
    primaryGauge: '04127200',
    gauges: [
      { id: '04126970', name: 'Above Brown Bridge Road near Mayfield' },
      { id: '04127200', name: 'At Beitner Road near Traverse City' },
    ],
  },
  {
    id: 'jordan',
    name: 'Jordan River',
    region: 'Northern Lower Michigan',
    regionCode: 'NLP',
    notes: 'Michigan\'s first Natural River. Cold, clear, and exceptional wild brook trout. One of the most pristine brook trout streams in the Lower Peninsula. Hex hatch in early summer.',
    species: ['brook', 'brown'],
    type: 'spring_creek',
    tier: 1,
    access: 'Graves Crossing, Webster Bridge, Rogers Road — good public access',
    regulations: 'Special brook trout regulations in season. Check DNR. Artificial only in designated sections.',
    primaryGauge: '04127800',
    gauges: [
      { id: '04127800', name: 'Near East Jordan' },
    ],
  },
  {
    id: 'pigeon',
    name: 'Pigeon River',
    region: 'Northern Lower Michigan',
    regionCode: 'NLP',
    notes: 'Pigeon River Country State Forest. Wild brook and brown trout in one of the most remote Lower Peninsula river corridors. Elk, bears, and outstanding solitude on the water.',
    species: ['brook', 'brown'],
    type: 'freestone',
    tier: 1,
    access: 'Pigeon Bridge Campground, Clark Bridge, Town Corner Lake Road',
    regulations: 'Special brook trout regulations. Check DNR for Pigeon River Country rules.',
    primaryGauge: '04128990',
    gauges: [
      { id: '04128990', name: 'Near Vanderbilt' },
    ],
  },
  {
    id: 'sturgeon-river-nlp',
    name: 'Sturgeon River (NLP)',
    region: 'Northern Lower Michigan',
    regionCode: 'NLP',
    notes: 'Northern LP gem flowing through Cheboygan County. Exceptional wild trout. Often called one of the best fly fishing rivers in Michigan that most people have never heard of. Cold, spring-influenced.',
    species: ['brown', 'brook'],
    type: 'freestone',
    tier: 1,
    access: 'Wolverine area, Rondo Road, Sturgeon Valley Road',
    regulations: 'General trout regulations. Check DNR for any special regs.',
    primaryGauge: '04127997',
    gauges: [
      { id: '04127997', name: 'Sturgeon River at Wolverine' },
    ],
  },
  {
    id: 'pine-river',
    name: 'Pine River',
    region: 'Northwest Lower Michigan',
    regionCode: 'NLP',
    notes: 'One of the top trout streams in the Lower Peninsula. Cold, swift, and wild — flows through Wexford and Lake counties. National Wild and Scenic designation. Excellent brown trout and a strong steelhead run.',
    species: ['brown', 'rainbow', 'steelhead'],
    type: 'freestone',
    tier: 1,
    access: 'Stronach Bridge, Lincoln Bridge, Elm Flats, Peterson Bridge',
    regulations: 'General trout. Check DNR for special regs on Pine River Corridor.',
    primaryGauge: '04125460',
    gauges: [
      { id: '04124500', name: 'East Branch near Tustin' },
      { id: '04125460', name: 'Pine River near Hoxeyville' },
    ],
  },
  {
    id: 'platte-river',
    name: 'Platte River',
    region: 'Northwest Lower Michigan',
    regionCode: 'NLP',
    notes: 'Short, spring-fed gem entering Lake Michigan near Honor. Crystal clear water, excellent wild trout, and a famous Coho salmon run in fall. Sleeping Bear Dunes National Lakeshore borders much of it.',
    species: ['brown', 'rainbow', 'steelhead'],
    type: 'spring_creek',
    tier: 1,
    access: 'Haze Road, Brethren, Honor — National Park Service access points',
    regulations: 'National Lakeshore rules apply in some sections. Check DNR and NPS.',
    primaryGauge: '04126740',
    gauges: [
      { id: '04126740', name: 'Platte River at Honor' },
    ],
  },
  {
    id: 'betsie-river',
    name: 'Betsie River',
    region: 'Northwest Lower Michigan',
    regionCode: 'NLP',
    notes: 'Flows through Benzie County to Lake Michigan. Classic west Michigan trout river with brown trout and excellent fall steelhead. Scenic, productive, and easily accessible from Benzonia to Frankfort.',
    species: ['brown', 'steelhead', 'rainbow'],
    type: 'freestone',
    tier: 1,
    access: 'Homestead Dam, Thompsonville, Benzonia, Frankfort',
    regulations: 'General trout regulations. Lake Michigan tributary — steelhead season dates apply.',
    primaryGauge: '04126600',
    gauges: [
      { id: '04126600', name: 'Betsie River near Benzonia' },
    ],
  },
  {
    id: 'little-manistee',
    name: 'Little Manistee River',
    region: 'Northwest Lower Michigan',
    regionCode: 'NLP',
    notes: 'Top steelhead river in Michigan. The Little Manistee weir above Freesoil is the source of Michigan\'s wild steelhead strain. Legendary run in April. Excellent brown trout in upper reaches.',
    species: ['steelhead', 'brown', 'rainbow'],
    type: 'freestone',
    tier: 1,
    access: 'Nine Mile Bridge, Old Grade Campground, Freesoil area',
    regulations: 'Artificial only sections near weir. Check DNR for Little Manistee special regs.',
    primaryGauge: '04126195',
    gauges: [
      { id: '04126195', name: 'At Nine Mile Bridge near Freesoil' },
    ],
  },
  {
    id: 'rifle-river',
    name: 'Rifle River',
    region: 'Northeast Lower Michigan',
    regionCode: 'NLP',
    notes: 'Classic Lower Peninsula trout stream flowing through Ogemaw County. Brown trout and steelhead. Recreational area offers excellent public access. Good early-season fishing when other rivers are running high.',
    species: ['brown', 'rainbow', 'steelhead'],
    type: 'freestone',
    tier: 1,
    access: 'Rifle River Recreation Area, Rose City, Sterling',
    regulations: 'General trout regulations.',
    primaryGauge: '04142000',
    gauges: [
      { id: '04142000', name: 'Rifle River near Sterling' },
    ],
  },
  {
    id: 'thunder-bay-river',
    name: 'Thunder Bay River',
    region: 'Northeast Lower Michigan',
    regionCode: 'NLP',
    notes: 'Northeast LP river flowing through Alpena County. Brown trout in upper reaches; Lake Huron steelhead in lower sections. Underutilized and underappreciated.',
    species: ['brown', 'steelhead'],
    type: 'freestone',
    tier: 2,
    access: 'Herron, Bolton area, Atlanta region (upper)',
    regulations: 'General trout regulations. Lake Huron tributary — check steelhead rules.',
    primaryGauge: '04133501',
    gauges: [
      { id: '04133501', name: 'Thunder Bay River at Herron Road' },
    ],
  },

  // ─────────────────────────────────────────────
  // WESTERN LOWER PENINSULA
  // ─────────────────────────────────────────────

  {
    id: 'white-river',
    name: 'White River',
    region: 'West-Central Lower Michigan',
    regionCode: 'WLP',
    notes: 'Flows through Muskegon and Oceana counties to White Lake. Brown trout in the headwaters and middle reaches; steelhead enter from Lake Michigan. Good public access along much of the length.',
    species: ['brown', 'steelhead'],
    type: 'freestone',
    tier: 1,
    access: 'Hesperia, White Cloud, Whitehall',
    regulations: 'General trout regulations.',
    primaryGauge: '04122200',
    gauges: [
      { id: '04122200', name: 'White River near Whitehall' },
    ],
  },
  {
    id: 'little-muskegon-river',
    name: 'Little Muskegon River',
    region: 'West-Central Lower Michigan',
    regionCode: 'WLP',
    notes: 'Tributary to the Muskegon with its own brown trout population. Smaller and more intimate than its famous neighbor. Good early-season dry fly fishing in the pine barrens country.',
    species: ['brown'],
    type: 'freestone',
    tier: 2,
    access: 'Oak Grove area, Mecosta County roads',
    regulations: 'General trout regulations.',
    primaryGauge: '04121944',
    gauges: [
      { id: '04121944', name: 'Little Muskegon River near Oak Grove' },
    ],
  },
  {
    id: 'clam-river',
    name: 'Clam River',
    region: 'West-Central Lower Michigan',
    regionCode: 'WLP',
    notes: 'Wexford County trout stream feeding into Cadillac area lakes. Cold, spring-influenced upper sections hold brown trout. Often fished as a half-day trip when targeting the Manistee or Pine.',
    species: ['brown', 'brook'],
    type: 'spring_creek',
    tier: 2,
    access: 'Vogel Center, Tustin area roads',
    regulations: 'General trout regulations.',
    primaryGauge: '04121300',
    gauges: [
      { id: '04121300', name: 'Clam River at Vogel Center' },
    ],
  },
  {
    id: 'rogue-river',
    name: 'Rogue River',
    region: 'West-Central Lower Michigan',
    regionCode: 'WLP',
    notes: 'Kent County gem flowing through Rockford. Outstanding wild brown trout in a river that runs right through a suburban area. Exceptional fishery for its location — one of the best urban trout streams anywhere.',
    species: ['brown', 'steelhead'],
    type: 'freestone',
    tier: 1,
    access: 'Rockford, White Pine Trail access, multiple city/county parks',
    regulations: 'General trout regulations.',
    primaryGauge: '04118500',
    gauges: [
      { id: '04118500', name: 'Rogue River near Rockford' },
    ],
  },
  {
    id: 'flat-river',
    name: 'Flat River',
    region: 'West-Central Lower Michigan',
    regionCode: 'WLP',
    notes: 'Grand River tributary with good brown trout in the upper reaches near Smyrna. Flows through Montcalm County. Spring fishing can be excellent before water warms.',
    species: ['brown'],
    type: 'freestone',
    tier: 1,
    access: 'Smyrna, Lowell area',
    regulations: 'General trout regulations.',
    primaryGauge: '04116500',
    gauges: [
      { id: '04116500', name: 'Flat River at Smyrna' },
    ],
  },
  {
    id: 'thornapple-river',
    name: 'Thornapple River',
    region: 'Southwest Lower Michigan',
    regionCode: 'WLP',
    notes: 'Grand River tributary with brown trout in the upper reaches. Flows through Hastings and Caledonia area. More of a smallmouth bass river in lower sections but trout in the cold headwaters.',
    species: ['brown'],
    type: 'freestone',
    tier: 2,
    access: 'Hastings area, Caledonia County parks',
    regulations: 'General trout regulations in designated trout waters.',
    primaryGauge: '04117500',
    gauges: [
      { id: '04117500', name: 'Thornapple River near Hastings' },
    ],
  },

  // ─────────────────────────────────────────────
  // CENTRAL LOWER PENINSULA
  // ─────────────────────────────────────────────

  {
    id: 'looking-glass-river',
    name: 'Looking Glass River',
    region: 'Central Lower Michigan',
    regionCode: 'CLP',
    notes: 'Clinton County gem with excellent wild brown trout. Spring-creek character in the upper sections near Portland. One of the best public trout streams in Central Michigan — remarkably underrated.',
    species: ['brown'],
    type: 'spring_creek',
    tier: 1,
    access: 'Eagle, Portland, Fowler — good public access at bridges',
    regulations: 'General trout regulations.',
    primaryGauge: '04114498',
    gauges: [
      { id: '04114498', name: 'Looking Glass River near Eagle' },
    ],
  },
  {
    id: 'maple-river-lp',
    name: 'Maple River',
    region: 'Central Lower Michigan',
    regionCode: 'CLP',
    notes: 'Gratiot/Clinton county river with wild brown trout. Cold tributaries and spring seeps maintain trout-quality temps in upper sections. Accessible and often overlooked — a good option for central Michigan anglers.',
    species: ['brown'],
    type: 'freestone',
    tier: 2,
    access: 'Maple Rapids, Ashley area',
    regulations: 'General trout regulations.',
    primaryGauge: '04115000',
    gauges: [
      { id: '04115000', name: 'Maple River at Maple Rapids' },
    ],
  },
  {
    id: 'pine-river-midland',
    name: 'Pine River (Mid-Michigan)',
    region: 'Central Lower Michigan',
    regionCode: 'CLP',
    notes: 'Flows through Midland and Isabella counties. Brown trout in cooler upper sections. Different from the famous Pine River in Wexford County — this is a Mid-Michigan stream with its own quality trout water.',
    species: ['brown'],
    type: 'freestone',
    tier: 2,
    access: 'Midland area, Sanford Lake region',
    regulations: 'General trout regulations.',
    primaryGauge: '04155500',
    gauges: [
      { id: '04155500', name: 'Pine River near Midland' },
    ],
  },
  {
    id: 'au-gres-river',
    name: 'Au Gres River',
    region: 'Northeast Lower Michigan',
    regionCode: 'CLP',
    notes: 'Flows through Arenac County to Saginaw Bay. Brown trout and steelhead. Cold upper sections from the Ogemaw Hills. Often overlooked despite good trout water in the upper reaches.',
    species: ['brown', 'steelhead'],
    type: 'freestone',
    tier: 2,
    access: 'Au Gres area, US-23 crossings, Arenac County roads',
    regulations: 'General trout regulations. Saginaw Bay tributary — check steelhead rules.',
    primaryGauge: '04138536',
    gauges: [
      { id: '04138536', name: 'Au Gres River near Au Gres' },
    ],
  },
];

// All unique gauge IDs across all rivers
export const ALL_GAUGE_IDS = [...new Set(
  RIVERS.flatMap(r => r.gauges.map(g => g.id))
)];

// Helper: get rivers by region
export function getRiversByRegion(regionCode) {
  return RIVERS.filter(r => r.regionCode === regionCode);
}

// Helper: get rivers by species
export function getRiversBySpecies(species) {
  return RIVERS.filter(r => r.species.includes(species));
}

// Region metadata
export const REGIONS = {
  UP:  { label: 'Upper Peninsula',        abbr: 'UP',  color: '#2e5f3c' },
  NLP: { label: 'Northern Lower Michigan', abbr: 'NLP', color: '#1a3a5c' },
  WLP: { label: 'Western Lower Michigan',  abbr: 'WLP', color: '#5c3a1a' },
  CLP: { label: 'Central Lower Michigan',  abbr: 'CLP', color: '#5c1a3a' },
};
