// Michigan Trout Report: Comprehensive Stream Registry
// 40+ verified USGS active gauges covering the full state
// parameterCd: 00060 = discharge (cfs), 00010 = water temp (C), 00065 = gage height (ft)
//
// Regions: 'UP' | 'NLP' | 'WLP' | 'CLP'
// Species: array of 'brook' | 'brown' | 'rainbow' | 'steelhead'
// Type: 'freestone' | 'spring_creek' | 'tailwater' | 'UP_headwater'
// Tier: 1 = direct gauge + temp, 2 = direct gauge flow-only, 3 = estimated (no gauge)

export const RIVERS = [

  // ─────────────────────────────────────────────
  // UPPER PENINSULA
  // ─────────────────────────────────────────────

  {
    id: 'black-river-up',
    name: 'Black River (UP)',
    region: 'Western Upper Peninsula',
    regionCode: 'UP',
    notes: 'Wild and remote brook trout fishery near Bessemer. Flows through the Porcupine Mountains area with stunning waterfalls. One of Michigan\'s most scenic trout streams.',
    species: ['brook', 'brown'],
    type: 'freestone',
    tier: 1,
    access: 'Black River Harbor Recreation Area, multiple county road access points',
    regulations: 'General trout regulations. Check DNR for special UP regulations.',
    gearType: 'general',
    primaryGauge: '04031000',
    gauges: [
      { id: '04031000', name: 'Black River near Bessemer' },
    ],
  },
  {
    id: 'presque-isle-river',
    name: 'Presque Isle River',
    region: 'Western Upper Peninsula',
    regionCode: 'UP',
    notes: 'Tumbles through dramatic gorges and waterfalls before emptying into Lake Superior. Excellent brook trout in the upper reaches. Part of Porcupine Mountains Wilderness.',
    species: ['brook', 'steelhead'],
    type: 'freestone',
    tier: 1,
    access: 'Porcupine Mountains State Park, US-2 bridges',
    regulations: 'General trout regulations. Lake Superior tributaries: check steelhead regs.',
    gearType: 'general',
    primaryGauge: '04032150',
    gauges: [
      { id: '04032150', name: 'Presque Isle River near Connorville' },
    ],
  },
  {
    id: 'sturgeon-river-up',
    name: 'Sturgeon River (UP)',
    region: 'Western Upper Peninsula',
    regionCode: 'UP',
    notes: 'One of Michigan\'s premier brook trout streams. Flows through the Ottawa National Forest: cold, clear, and remote. The native brook trout here are wild and beautiful.',
    species: ['brook'],
    type: 'UP_headwater',
    tier: 1,
    access: 'Ottawa National Forest roads, US-45 crossings',
    regulations: 'Special brook trout regulations apply: check DNR. Artificial lures only in sections.',
    gearType: 'artificial',
    primaryGauge: '04040500',
    gauges: [
      { id: '04040500', name: 'Sturgeon River near Sidnaw' },
      { id: '04041500', name: 'Sturgeon River near Alston' },
    ],
  },
  {
    id: 'ontonagon-river',
    name: 'Ontonagon River',
    region: 'Western Upper Peninsula',
    regionCode: 'UP',
    notes: 'Major UP river system with multiple branches. Steelhead and brown trout in lower sections; brook trout in the headwaters. Ottawa National Forest surrounds much of the river.',
    species: ['brook', 'brown', 'steelhead'],
    type: 'freestone',
    tier: 1,
    access: 'Rockland area, Ottawa NF access roads',
    regulations: 'General trout regulations. Lake Superior tributary: check steelhead season dates.',
    gearType: 'general',
    primaryGauge: '04040000',
    gauges: [
      { id: '04040000', name: 'Ontonagon River near Rockland' },
      { id: '04033000', name: 'Middle Branch near Paulding' },
      { id: '04036000', name: 'West Branch near Bergland' },
    ],
  },
  {
    id: 'trap-rock-river',
    name: 'Trap Rock River',
    region: 'Keweenaw Peninsula',
    regionCode: 'UP',
    notes: 'Remote Keweenaw Peninsula stream with wild brook trout. Native brook trout in cold headwaters. Lightly fished and extremely scenic. Spring steelhead run in lower river.',
    species: ['brook', 'steelhead'],
    type: 'UP_headwater',
    tier: 1,
    access: 'Keweenaw County roads: remote, minimal signage',
    regulations: 'General trout regulations.',
    gearType: 'general',
    primaryGauge: '04043050',
    gauges: [
      { id: '04043050', name: 'Trap Rock River near Lake Linden' },
    ],
  },
  {
    id: 'silver-river',
    name: 'Silver River',
    region: 'Baraga County, Upper Peninsula',
    regionCode: 'UP',
    notes: 'Small but productive brook trout stream in Baraga County. Classic UP headwater fishery: cold, clear, spring-fed. Often overlooked, rarely crowded.',
    species: ['brook'],
    type: 'UP_headwater',
    tier: 2,
    access: 'L\'Anse area county roads',
    regulations: 'General trout regulations.',
    gearType: 'general',
    primaryGauge: '04043150',
    gauges: [
      { id: '04043150', name: 'Silver River near L\'Anse' },
    ],
  },
  {
    id: 'salmon-trout-river',
    name: 'Salmon Trout River',
    region: 'Marquette County, Upper Peninsula',
    regionCode: 'UP',
    notes: 'Marquette County brook trout stream with wild native fish. Flows through Huron Mountains area: one of Michigan\'s most remote and least-accessible fisheries. Worth the effort.',
    species: ['brook'],
    type: 'UP_headwater',
    tier: 1,
    access: 'Big Bay area roads: remote, 4WD recommended',
    regulations: 'General trout regulations.',
    gearType: 'general',
    primaryGauge: '04043238',
    gauges: [
      { id: '04043238', name: 'Salmon Trout River near Big Bay' },
    ],
  },
  {
    id: 'au-train-river',
    name: 'Au Train River',
    region: 'Alger County, Upper Peninsula',
    regionCode: 'UP',
    notes: 'Flows through the Hiawatha National Forest into Au Train Lake and Lake Superior. Brook trout throughout; steelhead in spring. Beautiful forest setting near Pictured Rocks.',
    species: ['brook', 'steelhead'],
    type: 'freestone',
    tier: 1,
    access: 'Au Train, Hiawatha NF roads, M-28',
    regulations: 'General trout. Lake Superior tributary: steelhead season dates apply.',
    gearType: 'general',
    primaryGauge: '04044724',
    gauges: [
      { id: '04044724', name: 'Au Train River at Forest Lake' },
    ],
  },
  {
    id: 'miners-river',
    name: 'Miners River',
    region: 'Pictured Rocks, Upper Peninsula',
    regionCode: 'UP',
    notes: 'Flows through Pictured Rocks National Lakeshore. One of the most scenic trout streams in Michigan. Remote brook trout fishing with dramatic Lake Superior views nearby.',
    species: ['brook'],
    type: 'UP_headwater',
    tier: 2,
    access: 'Pictured Rocks NL: Miners Beach Road',
    regulations: 'National Lakeshore rules apply. Check NPS and DNR.',
    gearType: 'general',
    primaryGauge: '04044755',
    gauges: [
      { id: '04044755', name: 'Miners River near Munising' },
    ],
  },
  {
    id: 'tahquamenon-river',
    name: 'Tahquamenon River',
    region: 'Eastern Upper Peninsula',
    regionCode: 'UP',
    notes: 'One of the UP\'s great rivers. Famous for its tannin-stained falls. Brook trout in the upper watershed; steelhead enter the lower river. Tahquamenon Falls State Park surrounds much of it.',
    species: ['brook', 'steelhead', 'brown'],
    type: 'freestone',
    tier: 1,
    access: 'Tahquamenon Falls State Park, Paradise area',
    regulations: 'General trout. Lake Superior tributary: steelhead regs apply.',
    gearType: 'general',
    primaryGauge: '04045500',
    gauges: [
      { id: '04045500', name: 'Tahquamenon River near Paradise' },
    ],
  },
  {
    id: 'black-river-schoolcraft',
    name: 'Black River (Schoolcraft County)',
    region: 'Eastern Upper Peninsula',
    regionCode: 'UP',
    notes: 'Eastern UP brook trout stream in Schoolcraft County. Cold, tannin-stained waters produce wild native brookies. Remote and lightly fished: classic UP experience.',
    species: ['brook'],
    type: 'UP_headwater',
    tier: 2,
    access: 'Garnet area, Hiawatha National Forest roads',
    regulations: 'General trout regulations.',
    gearType: 'general',
    primaryGauge: '04046000',
    gauges: [
      { id: '04046000', name: 'Black River near Garnet' },
    ],
  },
  {
    id: 'paint-river',
    name: 'Paint River',
    region: 'Iron County, Upper Peninsula',
    regionCode: 'UP',
    notes: 'Central UP river system with wild brook trout. Flows through the Ottawa National Forest. Multiple forks converge in the Crystal Falls area. Good access and quality fishing.',
    species: ['brook', 'brown'],
    type: 'freestone',
    tier: 1,
    access: 'Crystal Falls area, Ottawa NF roads, M-69',
    regulations: 'General trout regulations.',
    gearType: 'general',
    primaryGauge: '04061500',
    gauges: [
      { id: '04061500', name: 'Paint River at Crystal Falls' },
      { id: '04062000', name: 'Paint River near Alpha' },
    ],
  },
  {
    id: 'iron-river',
    name: 'Iron River',
    region: 'Iron County, Upper Peninsula',
    regionCode: 'UP',
    notes: 'Iron County river with good brook trout fishing. Flows through the heart of the UP ironwood country. Accessible and underrated.',
    species: ['brook', 'brown'],
    type: 'freestone',
    tier: 1,
    access: 'Caspian, Iron River city access, US-2',
    regulations: 'General trout regulations.',
    gearType: 'general',
    primaryGauge: '04060500',
    gauges: [
      { id: '04060500', name: 'Iron River at Caspian' },
    ],
  },
  {
    id: 'michigamme-river',
    name: 'Michigamme River',
    region: 'Western Upper Peninsula',
    regionCode: 'UP',
    notes: 'Large UP river system below the Michigamme Reservoir. Good brown trout and steelhead in accessible sections. Flows through beautiful Ottawa National Forest terrain.',
    species: ['brown', 'brook', 'steelhead'],
    type: 'freestone',
    tier: 1,
    access: 'Crystal Falls area, Ottawa NF roads',
    regulations: 'General trout regulations.',
    gearType: 'general',
    primaryGauge: '04062500',
    gauges: [
      { id: '04062500', name: 'Michigamme River near Crystal Falls' },
    ],
  },
  {
    id: 'brule-river',
    name: 'Brule River (UP/Wisconsin Border)',
    region: 'Iron County, Upper Peninsula',
    regionCode: 'UP',
    notes: 'Forms the Michigan-Wisconsin state line. Excellent brook trout and brown trout. Both states require a valid license in their respective waters. Remote and often uncrowded.',
    species: ['brook', 'brown'],
    type: 'freestone',
    tier: 1,
    access: 'US-2 near Florence, WI: border river',
    regulations: 'Michigan or Wisconsin license required on respective side. Check both states\' regs.',
    gearType: 'general',
    primaryGauge: '04060993',
    gauges: [
      { id: '04060993', name: 'Brule River near Florence (border)' },
    ],
  },

  // ─────────────────────────────────────────────
  // NORTHERN LOWER PENINSULA
  // ─────────────────────────────────────────────

  {
    id: 'ausable',
    name: 'AuSable River',
    region: 'Northeast Lower Michigan',
    regionCode: 'NLP',
    notes: 'Holy Water stretch between Grayling and Mio. Premier wild trout fishery in the Midwest. Flies-only designated reaches, pristine spring-fed currents, legendary hatches. Home to Hex, Sulphur, and world-class rising brown trout.',
    species: ['brown', 'rainbow'],
    type: 'freestone',
    tier: 1,
    access: 'Grayling, Mio, Burton\'s Landing, Wakeley Bridge: extensive public access',
    regulations: 'Special regulations on Holy Water (flies-only, C&R). Check DNR for designated water rules.',
    gearType: 'general',
    primaryGauge: '04136500',
    gauges: [
      { id: '04135800', name: 'North Branch at Lovells' },
      { id: '04135700', name: 'South Branch near Luzerne' },
      { id: '04136000', name: 'Main Branch near Red Oak' },
      { id: '04136500', name: 'Main Branch at Mio' },
      { id: '04136900', name: 'Main Branch near McKinley' },
      { id: '04137005', name: 'Main Branch near Curtisville' },
      { id: '04137500', name: 'Main Branch near AuSable' },
      { id: '041377255', name: 'Main Branch near Oscoda' },
    ],
  },
  {
    id: 'manistee',
    name: 'Manistee River',
    region: 'Northwest Lower Michigan',
    regionCode: 'NLP',
    notes: 'Headwaters near Grayling, excellent brown trout in the upper reaches and world-class steelhead in lower sections. One of Michigan\'s longest and most diverse trout rivers.',
    species: ['brown', 'rainbow', 'steelhead'],
    type: 'freestone',
    tier: 1,
    access: 'Grayling (upper), CCC Bridge, High Bridge, Tippy Dam area',
    regulations: 'Various special regulations by section. Check DNR for current rules.',
    gearType: 'general',
    primaryGauge: '04123500',
    gauges: [
      { id: '04123500', name: 'Near Grayling (upper)' },
      { id: '04124000', name: 'Near Sherman (mid)' },
      { id: '04124200', name: 'Near Mesick' },
      { id: '04125550', name: 'Near Wellston (lower)' },
    ],
  },
  {
    id: 'pere-marquette',
    name: 'Pere Marquette River',
    region: 'West-Central Lower Michigan',
    regionCode: 'NLP',
    notes: 'Wild and Scenic designated. Premier steelhead and brown trout river. Gin-clear flows through Mason and Lake counties. One of the top 10 trout streams in North America.',
    species: ['brown', 'rainbow', 'steelhead'],
    type: 'freestone',
    tier: 1,
    access: 'Walhalla, Branch Bridge, Sulak, Scottville: state and national forest access',
    regulations: 'Flies-only designated section below Gleeson\'s Landing. Check DNR for full rules.',
    gearType: 'general',
    primaryGauge: '04122500',
    gauges: [
      { id: '04122500', name: 'At Scottville' },
    ],
  },
  {
    id: 'muskegon',
    name: 'Muskegon River',
    region: 'West-Central Lower Michigan',
    regionCode: 'NLP',
    notes: 'Tailwater fishery below Croton Dam. Year-round trout and steelhead thanks to cold, stable dam releases. One of the most productive and accessible trout rivers in Michigan.',
    species: ['brown', 'rainbow', 'steelhead'],
    type: 'tailwater',
    tier: 1,
    access: 'Croton Dam, Newaygo, Bridgeton: well-maintained public access sites',
    regulations: 'Catch-and-release season extended due to tailwater designation. Check DNR.',
    gearType: 'general',
    primaryGauge: '04121970',
    gauges: [
      { id: '04121500', name: 'At Evart (upper)' },
      { id: '04121650', name: 'At Big Rapids (mid-upper)' },
      { id: '04121970', name: 'Near Croton (tailwater)' },
      { id: '04122001', name: 'At Newaygo (lower)' },
    ],
  },
  {
    id: 'boardman',
    name: 'Boardman River',
    region: 'Northwest Lower Michigan',
    regionCode: 'NLP',
    notes: 'Flows through Traverse City. Quality wild brown trout fishery through Fife Lake and Boardman Valley. Underrated and often uncrowded compared to its famous neighbors.',
    species: ['brown', 'brook'],
    type: 'freestone',
    tier: 1,
    access: 'Brown Bridge Road, Scheck\'s Place, Boardman Valley Road',
    regulations: 'General trout. Check DNR for any designated special regulations sections.',
    gearType: 'general',
    primaryGauge: '04127200',
    gauges: [
      { id: '04126970', name: 'Above Brown Bridge Road near Mayfield' },
      { id: '04127200', name: 'At Beitner Road near Traverse City' },
    ],
  },
  {
    id: 'jordan',
    name: 'Jordan River',
    region: 'Northern Lower Michigan',
    regionCode: 'NLP',
    notes: 'Michigan\'s first Natural River. Cold, clear, and exceptional wild brook trout. One of the most pristine brook trout streams in the Lower Peninsula. Hex hatch in early summer.',
    species: ['brook', 'brown'],
    type: 'spring_creek',
    tier: 1,
    access: 'Graves Crossing, Webster Bridge, Rogers Road: good public access',
    regulations: 'Special brook trout regulations in season. Check DNR. Artificial only in designated sections.',
    gearType: 'general',
    primaryGauge: '04127800',
    gauges: [
      { id: '04127800', name: 'Near East Jordan' },
    ],
  },
  {
    id: 'pigeon',
    name: 'Pigeon River',
    region: 'Northern Lower Michigan',
    regionCode: 'NLP',
    notes: 'Pigeon River Country State Forest. Wild brook and brown trout in one of the most remote Lower Peninsula river corridors. Elk, bears, and outstanding solitude on the water.',
    species: ['brook', 'brown'],
    type: 'freestone',
    tier: 1,
    access: 'Pigeon Bridge Campground, Clark Bridge, Town Corner Lake Road',
    regulations: 'Special brook trout regulations. Check DNR for Pigeon River Country rules.',
    gearType: 'general',
    primaryGauge: '04128990',
    gauges: [
      { id: '04128990', name: 'Near Vanderbilt' },
    ],
  },
  {
    id: 'sturgeon-river-nlp',
    name: 'Sturgeon River (NLP)',
    region: 'Northern Lower Michigan',
    regionCode: 'NLP',
    notes: 'Northern LP gem flowing through Cheboygan County. Exceptional wild trout. Often called one of the best fly fishing rivers in Michigan that most people have never heard of. Cold, spring-influenced.',
    species: ['brown', 'brook'],
    type: 'freestone',
    tier: 1,
    access: 'Wolverine area, Rondo Road, Sturgeon Valley Road',
    regulations: 'General trout regulations. Check DNR for any special regs.',
    gearType: 'general',
    primaryGauge: '04127997',
    gauges: [
      { id: '04127997', name: 'Sturgeon River at Wolverine' },
    ],
  },
  {
    id: 'pine-river',
    name: 'Pine River',
    region: 'Northwest Lower Michigan',
    regionCode: 'NLP',
    notes: 'One of the top trout streams in the Lower Peninsula. Cold, swift, and wild: flows through Wexford and Lake counties. National Wild and Scenic designation. Excellent brown trout and a strong steelhead run.',
    species: ['brown', 'rainbow', 'steelhead'],
    type: 'freestone',
    tier: 1,
    access: 'Stronach Bridge, Lincoln Bridge, Elm Flats, Peterson Bridge',
    regulations: 'General trout. Check DNR for special regs on Pine River Corridor.',
    gearType: 'general',
    primaryGauge: '04125460',
    gauges: [
      { id: '04124500', name: 'East Branch near Tustin' },
      { id: '04125460', name: 'Pine River near Hoxeyville' },
    ],
  },
  {
    id: 'platte-river',
    name: 'Platte River',
    region: 'Northwest Lower Michigan',
    regionCode: 'NLP',
    notes: 'Short, spring-fed gem entering Lake Michigan near Honor. Crystal clear water, excellent wild trout, and a famous Coho salmon run in fall. Sleeping Bear Dunes National Lakeshore borders much of it.',
    species: ['brown', 'rainbow', 'steelhead'],
    type: 'spring_creek',
    tier: 1,
    access: 'Haze Road, Brethren, Honor: National Park Service access points',
    regulations: 'National Lakeshore rules apply in some sections. Check DNR and NPS.',
    gearType: 'general',
    primaryGauge: '04126740',
    gauges: [
      { id: '04126740', name: 'Platte River at Honor' },
    ],
  },
  {
    id: 'betsie-river',
    name: 'Betsie River',
    region: 'Northwest Lower Michigan',
    regionCode: 'NLP',
    notes: 'Flows through Benzie County to Lake Michigan. Classic west Michigan trout river with brown trout and excellent fall steelhead. Scenic, productive, and easily accessible from Benzonia to Frankfort.',
    species: ['brown', 'steelhead', 'rainbow'],
    type: 'freestone',
    tier: 1,
    access: 'Homestead Dam, Thompsonville, Benzonia, Frankfort',
    regulations: 'General trout regulations. Lake Michigan tributary: steelhead season dates apply.',
    gearType: 'general',
    primaryGauge: '04126600',
    gauges: [
      { id: '04126600', name: 'Betsie River near Benzonia' },
    ],
  },
  {
    id: 'little-manistee',
    name: 'Little Manistee River',
    region: 'Northwest Lower Michigan',
    regionCode: 'NLP',
    notes: 'Top steelhead river in Michigan. The Little Manistee weir above Freesoil is the source of Michigan\'s wild steelhead strain. Legendary run in April. Excellent brown trout in upper reaches.',
    species: ['steelhead', 'brown', 'rainbow'],
    type: 'freestone',
    tier: 1,
    access: 'Nine Mile Bridge, Old Grade Campground, Freesoil area',
    regulations: 'Artificial only sections near weir. Check DNR for Little Manistee special regs.',
    gearType: 'general',
    primaryGauge: '04126195',
    gauges: [
      { id: '04126195', name: 'At Nine Mile Bridge near Freesoil' },
    ],
  },
  {
    id: 'rifle-river',
    name: 'Rifle River',
    region: 'Northeast Lower Michigan',
    regionCode: 'NLP',
    notes: 'Classic Lower Peninsula trout stream flowing through Ogemaw County. Brown trout and steelhead. Recreational area offers excellent public access. Good early-season fishing when other rivers are running high.',
    species: ['brown', 'rainbow', 'steelhead'],
    type: 'freestone',
    tier: 1,
    access: 'Rifle River Recreation Area, Rose City, Sterling',
    regulations: 'General trout regulations.',
    gearType: 'general',
    primaryGauge: '04142000',
    gauges: [
      { id: '04142000', name: 'Rifle River near Sterling' },
    ],
    tributaries: [
      {
        id: 'klacking-creek',
        name: 'Klacking Creek',
        slug: 'klacking-creek-michigan',
        species: ['brown', 'brook'],
        type: 'spring_creek',
        notes: 'Excellent brown trout tributary of the Rifle. Fish over 14 inches common; 20-inch browns documented. Cold, spring-fed water through Ogemaw County. DNR research dating to 1951 confirms strong populations.',
        access: 'E. Peters Road crossing, Campbell Road, N. Campbell Road, Townline Road crossing. Multiple road bridges through West Branch and Klacking townships.',
        regulations: 'General trout regulations. Designated trout stream.',
    gearType: 'general',
        wading: 'Easy to moderate. Small stream, gravel and sand bottom. Hip waders or wet-wading in summer. Chest waders in spring.',
        description: 'Klacking Creek is one of the Rifle River\'s premier trout tributaries, flowing through Ogemaw County before joining the Rifle south of West Branch. DNR fisheries research going back to 1951 documented healthy brown trout populations with fish regularly exceeding 14 inches. The creek also holds brook trout in its coldest headwater sections.',
        description2: 'This is small water that rewards stealth and patience. Brown trout here are wild, wary, and surprisingly large for the creek\'s size. Spring caddis and Hendrickson hatches bring fish to the surface. Summer terrestrials (ants, beetles, hoppers) are productive along the brushy banks. Approach low, cast short, and use light tippet (5X-6X). The E. Peters Road crossing is the most popular access, but walking upstream from any road bridge will find less-pressured water.',
      },
      {
        id: 'houghton-creek',
        name: 'Houghton Creek',
        slug: 'houghton-creek-michigan',
        species: ['brown', 'brook'],
        type: 'spring_creek',
        notes: 'The Rifle\'s most famous tributary. A 37-inch brown trout caught here in 1952 held the state record for years. Cold, spring-fed, excellent spawning habitat.',
        access: 'Houghton Creek Road (off M-55), Rifle River Recreation Area. Bridge crossings through Rose and Churchill townships.',
        regulations: 'General trout regulations. Designated trout stream.',
    gearType: 'general',
        wading: 'Easy. Small, wadeable creek. Hip waders sufficient most of the year.',
        description: 'Houghton Creek is the most celebrated tributary in the Rifle River system. A 37-inch brown trout caught here in 1952 held the Michigan state record for years. The creek flows through the Rifle River Recreation Area, with cold spring water maintaining ideal trout temperatures even in summer.',
        description2: 'The upper station in the Recreation Area receives some pressure from park visitors, but most anglers stick close to the campground. Walking upstream through the woods reveals lightly fished water with wild browns holding in every bend. Small dry flies (#16-20 Adams, BWOs) and nymphs are the standard approach. The creek is also an important brown trout spawning tributary in fall.',
      },
      {
        id: 'gamble-creek',
        name: 'Gamble Creek',
        slug: 'gamble-creek-michigan',
        species: ['brown', 'brook'],
        type: 'spring_creek',
        notes: 'Found within the Rifle River Recreation Area. Similar trout populations to Klacking Creek. Less traffic than the main Rifle despite holding comparable fish.',
        access: 'Rifle River Recreation Area internal roads. M-33 crossing.',
        regulations: 'General trout regulations. Designated trout stream.',
    gearType: 'general',
        wading: 'Easy. Very small stream. Wet-wading or hip waders.',
        description: 'Gamble Creek flows through the Rifle River Recreation Area in Ogemaw County and sees significantly less angling pressure than the main Rifle despite holding similar brown trout populations. DNR research since the 1950s has tracked trout here alongside Klacking and Houghton creeks.',
        description2: 'Hiking upstream from the Recreation Area roads puts you on water that most anglers never see. The creek is small enough that accurate short casts and careful wading matter more than fly selection. Attractor dries (#14-16 Adams, Royal Wulff) work well in the riffles, with small nymphs (#16-18 Pheasant Tail) in the deeper pools.',
      },
      {
        id: 'wilkins-creek',
        name: 'Wilkins Creek',
        slug: 'wilkins-creek-michigan',
        species: ['brown', 'brook'],
        type: 'spring_creek',
        notes: 'Quality Rifle tributary in Ogemaw County. Brook trout in the headwaters, browns in the lower sections. Cold and lightly fished.',
        access: 'County road crossings in Klacking Township. Less signed than Klacking or Houghton.',
        regulations: 'General trout regulations.',
    gearType: 'general',
        wading: 'Easy but brushy. Short rod recommended. Hip waders.',
        description: 'Wilkins Creek is one of the quieter Rifle River tributaries. Brook trout occupy the coldest headwater sections, with browns taking over in the lower reaches. The creek is small, brushy, and lightly fished.',
        description2: 'Bring a short rod (6-7 feet) and be prepared to roll cast. The banks are overgrown in many sections, which is what keeps the pressure off and the fish in. Small dries and nymphs dropped into the deeper pockets will find fish.',
      },
      {
        id: 'eddy-creek',
        name: 'Eddy Creek',
        slug: 'eddy-creek-michigan',
        species: ['brown', 'brook'],
        type: 'spring_creek',
        notes: 'The only good trout tributary below Selkirk on the Rifle system. Brook trout and browns in a small, cold creek.',
        access: 'County road crossings south of Selkirk, Ogemaw County.',
        regulations: 'General trout regulations.',
    gearType: 'general',
        wading: 'Easy. Very small stream.',
        description: 'Eddy Creek is notable as the only quality trout tributary of the Rifle River below the town of Selkirk. While the other strong tributaries (Klacking, Houghton, Gamble, Wilkins) all enter above Selkirk, Eddy Creek provides cold-water habitat and trout fishing in the mid-river system.',
        description2: 'A small, modest creek that holds both browns and brook trout. Not a destination by itself, but worth exploring if you are fishing the Rifle in the Selkirk area and want to try something different. Small flies and a careful approach.',
      },
    ],
  },
  {
    id: 'thunder-bay-river',
    name: 'Thunder Bay River',
    region: 'Northeast Lower Michigan',
    regionCode: 'NLP',
    notes: 'Northeast LP river flowing through Alpena County. Brown trout in upper reaches; Lake Huron steelhead in lower sections. Underutilized and underappreciated.',
    species: ['brown', 'steelhead'],
    type: 'freestone',
    tier: 2,
    access: 'Herron, Bolton area, Atlanta region (upper)',
    regulations: 'General trout regulations. Lake Huron tributary: check steelhead rules.',
    gearType: 'general',
    primaryGauge: '04133501',
    gauges: [
      { id: '04133501', name: 'Thunder Bay River at Herron Road' },
    ],
  },

  // ─────────────────────────────────────────────
  // WESTERN LOWER PENINSULA
  // ─────────────────────────────────────────────

  {
    id: 'white-river',
    name: 'White River',
    region: 'West-Central Lower Michigan',
    regionCode: 'WLP',
    notes: 'Flows through Muskegon and Oceana counties to White Lake. Brown trout in the headwaters and middle reaches; steelhead enter from Lake Michigan. Good public access along much of the length.',
    species: ['brown', 'steelhead'],
    type: 'freestone',
    tier: 1,
    access: 'Hesperia, White Cloud, Whitehall',
    regulations: 'General trout regulations.',
    gearType: 'general',
    primaryGauge: '04122200',
    gauges: [
      { id: '04122200', name: 'White River near Whitehall' },
    ],
  },
  {
    id: 'little-muskegon-river',
    name: 'Little Muskegon River',
    region: 'West-Central Lower Michigan',
    regionCode: 'WLP',
    notes: 'Tributary to the Muskegon with its own brown trout population. Smaller and more intimate than its famous neighbor. Good early-season dry fly fishing in the pine barrens country.',
    species: ['brown'],
    type: 'freestone',
    tier: 2,
    access: 'Oak Grove area, Mecosta County roads',
    regulations: 'General trout regulations.',
    gearType: 'general',
    primaryGauge: '04121944',
    gauges: [
      { id: '04121944', name: 'Little Muskegon River near Oak Grove' },
    ],
  },
  {
    id: 'clam-river',
    name: 'Clam River',
    region: 'West-Central Lower Michigan',
    regionCode: 'WLP',
    notes: 'Wexford County trout stream feeding into Cadillac area lakes. Cold, spring-influenced upper sections hold brown trout. Often fished as a half-day trip when targeting the Manistee or Pine.',
    species: ['brown', 'brook'],
    type: 'spring_creek',
    tier: 2,
    access: 'Vogel Center, Tustin area roads',
    regulations: 'General trout regulations.',
    gearType: 'general',
    primaryGauge: '04121300',
    gauges: [
      { id: '04121300', name: 'Clam River at Vogel Center' },
    ],
  },
  {
    id: 'rogue-river',
    name: 'Rogue River',
    region: 'West-Central Lower Michigan',
    regionCode: 'WLP',
    notes: 'Kent County gem flowing through Rockford. Outstanding wild brown trout in a river that runs right through a suburban area. Exceptional fishery for its location: one of the best urban trout streams anywhere.',
    species: ['brown', 'steelhead'],
    type: 'freestone',
    tier: 1,
    access: 'Rockford, White Pine Trail access, multiple city/county parks',
    regulations: 'General trout regulations.',
    gearType: 'general',
    primaryGauge: '04118500',
    gauges: [
      { id: '04118500', name: 'Rogue River near Rockford' },
    ],
  },
  {
    id: 'flat-river',
    name: 'Flat River',
    region: 'West-Central Lower Michigan',
    regionCode: 'WLP',
    notes: 'Grand River tributary with good brown trout in the upper reaches near Smyrna. Flows through Montcalm County. Spring fishing can be excellent before water warms.',
    species: ['brown'],
    type: 'freestone',
    tier: 1,
    access: 'Smyrna, Lowell area',
    regulations: 'General trout regulations.',
    gearType: 'general',
    primaryGauge: '04116500',
    gauges: [
      { id: '04116500', name: 'Flat River at Smyrna' },
    ],
  },
  {
    id: 'thornapple-river',
    name: 'Thornapple River',
    region: 'Southwest Lower Michigan',
    regionCode: 'WLP',
    notes: 'Grand River tributary with brown trout in the upper reaches. Flows through Hastings and Caledonia area. More of a smallmouth bass river in lower sections but trout in the cold headwaters.',
    species: ['brown'],
    type: 'freestone',
    tier: 2,
    access: 'Hastings area, Caledonia County parks',
    regulations: 'General trout regulations in designated trout waters.',
    gearType: 'general',
    primaryGauge: '04117500',
    gauges: [
      { id: '04117500', name: 'Thornapple River near Hastings' },
    ],
  },

  // ─────────────────────────────────────────────
  // CENTRAL LOWER PENINSULA
  // ─────────────────────────────────────────────

  {
    id: 'looking-glass-river',
    name: 'Looking Glass River',
    region: 'Central Lower Michigan',
    regionCode: 'CLP',
    notes: 'Clinton County gem with excellent wild brown trout. Spring-creek character in the upper sections near Portland. One of the best public trout streams in Central Michigan: remarkably underrated.',
    species: ['brown'],
    type: 'spring_creek',
    tier: 1,
    access: 'Eagle, Portland, Fowler: good public access at bridges',
    regulations: 'General trout regulations.',
    gearType: 'general',
    primaryGauge: '04114498',
    gauges: [
      { id: '04114498', name: 'Looking Glass River near Eagle' },
    ],
  },
  {
    id: 'maple-river-lp',
    name: 'Maple River',
    region: 'Central Lower Michigan',
    regionCode: 'CLP',
    notes: 'Gratiot/Clinton county river with wild brown trout. Cold tributaries and spring seeps maintain trout-quality temps in upper sections. Accessible and often overlooked: a good option for central Michigan anglers.',
    species: ['brown'],
    type: 'freestone',
    tier: 2,
    access: 'Maple Rapids, Ashley area',
    regulations: 'General trout regulations.',
    gearType: 'general',
    primaryGauge: '04115000',
    gauges: [
      { id: '04115000', name: 'Maple River at Maple Rapids' },
    ],
  },
  {
    id: 'pine-river-midland',
    name: 'Pine River (Mid-Michigan)',
    region: 'Central Lower Michigan',
    regionCode: 'CLP',
    notes: 'Flows through Midland and Isabella counties. Brown trout in cooler upper sections. Different from the famous Pine River in Wexford County: this is a Mid-Michigan stream with its own quality trout water.',
    species: ['brown'],
    type: 'freestone',
    tier: 2,
    access: 'Midland area, Sanford Lake region',
    regulations: 'General trout regulations.',
    gearType: 'general',
    primaryGauge: '04155500',
    gauges: [
      { id: '04155500', name: 'Pine River near Midland' },
    ],
  },
  {
    id: 'au-gres-river',
    name: 'Au Gres River',
    region: 'Northeast Lower Michigan',
    regionCode: 'CLP',
    notes: 'Flows through Arenac County to Saginaw Bay. Brown trout and steelhead. Cold upper sections from the Ogemaw Hills. Often overlooked despite good trout water in the upper reaches.',
    species: ['brown', 'steelhead'],
    type: 'freestone',
    tier: 2,
    access: 'Au Gres area, US-23 crossings, Arenac County roads',
    regulations: 'General trout regulations. Saginaw Bay tributary: check steelhead rules.',
    gearType: 'general',
    primaryGauge: '04138536',
    gauges: [
      { id: '04138536', name: 'Au Gres River near Au Gres' },
    ],
  },

  // ── NEW RIVERS (Phase 1 expansion: 25 additional gauged trout streams) ──

  {
    id: 'escanaba-river',
    name: 'Escanaba River',
    region: 'Central Upper Peninsula',
    regionCode: 'UP',
    notes: 'One of the Upper Peninsula\'s finest trout rivers. The Escanaba drains over 900 square miles through the Copper Country State Forest. Brook trout in the upper branches, browns and rainbows in the main stem near Cornell.',
    species: ['brook', 'brown', 'rainbow'],
    type: 'freestone',
    tier: 1,
    access: 'Cornell area, M-95 crossings, county forest roads. USFS campgrounds along the Middle Branch.',
    regulations: 'Type 2 on some sections. Check DNR FO-200 for specific boundaries.',
    gearType: 'general',
    primaryGauge: '04059000',
    gauges: [
      { id: '04059000', name: 'Escanaba River at Cornell' },
      { id: '04059034', name: 'Escanaba River near Wells' },
      { id: '04057800', name: 'Middle Branch Escanaba at Humboldt' },
      { id: '04058100', name: 'Middle Branch Escanaba near Princeton' },
    ],
  },
  {
    id: 'ford-river',
    name: 'Ford River',
    region: 'Central Upper Peninsula',
    regionCode: 'UP',
    notes: 'Delta County river with brook and brown trout in the upper reaches. Flows south to Lake Michigan near Escanaba.',
    species: ['brook', 'brown'],
    type: 'freestone',
    tier: 1,
    access: 'Hyde area, county road bridge crossings, Escanaba State Forest roads',
    regulations: 'General trout regulations.',
    gearType: 'general',
    primaryGauge: '04059500',
    gauges: [
      { id: '04059500', name: 'Ford River near Hyde' },
    ],
  },
  {
    id: 'cedar-river-up',
    name: 'Cedar River (UP)',
    region: 'Central Upper Peninsula',
    regionCode: 'UP',
    notes: 'Menominee County river flowing to Green Bay. Brook trout in headwaters. Spring steelhead run from Green Bay.',
    species: ['brook', 'brown', 'steelhead'],
    type: 'freestone',
    tier: 1,
    access: 'County Road 366 crossing, Cedar River village area',
    regulations: 'General trout regulations. Green Bay tributary: check steelhead season dates.',
    gearType: 'general',
    primaryGauge: '04059750',
    gauges: [
      { id: '04059750', name: 'Cedar River near Cedar River' },
    ],
  },
  {
    id: 'paint-river-up',
    name: 'Paint River',
    region: 'Western Upper Peninsula',
    regionCode: 'UP',
    notes: 'National Wild and Scenic River with exceptional brook and brown trout. Blue Ribbon water through Iron County.',
    species: ['brook', 'brown'],
    type: 'freestone',
    tier: 1,
    access: 'Crystal Falls area, US-2 crossings, Ottawa National Forest roads',
    regulations: 'Complex regs: 10-inch brook trout minimum on South Branch. Type 2/GR sections. Consult FO-200.',
    gearType: 'gear_restricted',
    primaryGauge: '04061500',
    gauges: [
      { id: '04061500', name: 'Paint River at Crystal Falls' },
      { id: '04062000', name: 'Paint River near Alpha' },
    ],
  },
  {
    id: 'sturgeon-river-nahma',
    name: 'Sturgeon River (Nahma)',
    region: 'Central Upper Peninsula',
    regionCode: 'UP',
    notes: 'Alger/Delta county stream near Nahma Junction. Brook trout in the headwaters. Lightly fished.',
    species: ['brook', 'brown'],
    type: 'freestone',
    tier: 2,
    access: 'Nahma Junction area, county road crossings',
    regulations: 'General trout regulations.',
    gearType: 'general',
    primaryGauge: '04057510',
    gauges: [
      { id: '04057510', name: 'Sturgeon River near Nahma Junction' },
    ],
  },
  {
    id: 'salmon-trout-eb',
    name: 'East Branch Salmon Trout River',
    region: 'Marquette County, Upper Peninsula',
    regionCode: 'UP',
    notes: 'Remote Huron Mountains brook trout creek. Native fish in pristine headwaters. Coaster brook trout conservation area.',
    species: ['brook'],
    type: 'UP_headwater',
    tier: 2,
    access: 'Dodge City area, 4WD forest roads. Remote and minimally signed.',
    regulations: 'General trout regulations. Please practice catch-and-release on native brook trout.',
    gearType: 'general',
    primaryGauge: '04043244',
    gauges: [
      { id: '04043244', name: 'East Branch Salmon Trout River near Dodge City' },
    ],
  },
  {
    id: 'cisco-branch-ontonagon',
    name: 'Cisco Branch Ontonagon River',
    region: 'Western Upper Peninsula',
    regionCode: 'UP',
    notes: 'Tributary of the Ontonagon flowing from Cisco Lake through Ottawa National Forest. Brook trout in cold headwaters.',
    species: ['brook', 'brown'],
    type: 'freestone',
    tier: 2,
    access: 'Cisco Lake outlet, Ottawa National Forest roads off US-2',
    regulations: 'General trout regulations.',
    gearType: 'general',
    primaryGauge: '04037500',
    gauges: [
      { id: '04037500', name: 'Cisco Branch Ontonagon at Cisco Lake Outlet' },
    ],
  },
  {
    id: 'pine-river-rudyard',
    name: 'Pine River (Rudyard)',
    region: 'Eastern Upper Peninsula',
    regionCode: 'UP',
    notes: 'Chippewa County stream south of Sault Ste. Marie. Brook trout in cold upper sections.',
    species: ['brook', 'brown'],
    type: 'freestone',
    tier: 2,
    access: 'Rudyard area, county road crossings',
    regulations: 'General trout regulations.',
    gearType: 'general',
    primaryGauge: '04127917',
    gauges: [
      { id: '04127917', name: 'Pine River near Rudyard' },
    ],
  },
  {
    id: 'menominee-river',
    name: 'Menominee River',
    region: 'Western Upper Peninsula',
    regionCode: 'UP',
    notes: 'Michigan-Wisconsin border river. Large system with steelhead, brown trout, and brook trout in tributaries.',
    species: ['brown', 'steelhead', 'brook'],
    type: 'freestone',
    tier: 1,
    access: 'White Rapids Dam area, US-2 crossings near Banat',
    regulations: 'Michigan-Wisconsin boundary water regulations. Check both states.',
    gearType: 'general',
    primaryGauge: '04066030',
    gauges: [
      { id: '04066030', name: 'Menominee River at White Rapids Dam' },
    ],
  },
  {
    id: 'sturgeon-river-loretto',
    name: 'Sturgeon River (Loretto)',
    region: 'Central Upper Peninsula',
    regionCode: 'UP',
    notes: 'Dickinson/Menominee county stream. Brook trout in headwaters, browns in lower sections.',
    species: ['brook', 'brown'],
    type: 'freestone',
    tier: 2,
    access: 'US Highway 2 crossing at Loretto',
    regulations: 'General trout regulations.',
    gearType: 'general',
    primaryGauge: '04065650',
    gauges: [
      { id: '04065650', name: 'Sturgeon River at US-2 at Loretto' },
    ],
  },

  // ── Northern Lower Peninsula additions ──

  {
    id: 'pine-river-oscoda',
    name: 'Pine River (Oscoda)',
    region: 'Northeast Lower Michigan',
    regionCode: 'NLP',
    notes: 'AuSable tributary in Alcona/Iosco counties. Brown and brook trout. Flows through Huron National Forest.',
    species: ['brown', 'brook'],
    type: 'freestone',
    tier: 2,
    access: 'Kings Corner Road crossing, Huron NF roads near Oscoda',
    regulations: 'General trout regulations.',
    gearType: 'general',
    primaryGauge: '04137680',
    gauges: [
      { id: '04137680', name: 'Pine River at Kings Corner Rd near Oscoda' },
    ],
  },
  {
    id: 'chippewa-creek-evart',
    name: 'Chippewa Creek',
    region: 'Central Lower Michigan',
    regionCode: 'NLP',
    notes: 'Osceola County tributary of the Muskegon River near Evart. Small but cold creek with brown trout.',
    species: ['brown', 'brook'],
    type: 'spring_creek',
    tier: 2,
    access: '90th Avenue crossing near Evart',
    regulations: 'General trout regulations.',
    gearType: 'general',
    primaryGauge: '04121494',
    gauges: [
      { id: '04121494', name: 'Chippewa Creek near Evart' },
    ],
  },
  {
    id: 'muskegon-bridgeton',
    name: 'Muskegon River (Lower)',
    region: 'West-Central Lower Michigan',
    regionCode: 'WLP',
    notes: 'Lower Muskegon below Croton Dam. Big tailwater with steelhead, brown trout, and salmon runs.',
    species: ['brown', 'steelhead', 'rainbow'],
    type: 'tailwater',
    tier: 1,
    access: 'Bridgeton, Newaygo, Pine Street launch. Multiple public access sites.',
    regulations: 'Complex: Croton Dam to Newaygo Dam has specific regs. Check FO-200.',
    gearType: 'general',
    primaryGauge: '04122025',
    gauges: [
      { id: '04122025', name: 'Muskegon River at Bridgeton' },
      { id: '04122001', name: 'Muskegon River at Bridge St, Newaygo' },
    ],
  },
  {
    id: 'bear-creek-muskegon',
    name: 'Bear Creek',
    region: 'West-Central Lower Michigan',
    regionCode: 'WLP',
    notes: 'Muskegon County tributary. Small, cold stream with brown trout. Urban-adjacent but holds fish.',
    species: ['brown'],
    type: 'freestone',
    tier: 2,
    access: 'Near Muskegon, county road crossings',
    regulations: 'General trout regulations.',
    gearType: 'general',
    primaryGauge: '04122100',
    gauges: [
      { id: '04122100', name: 'Bear Creek near Muskegon' },
    ],
  },
  {
    id: 'east-branch-au-gres',
    name: 'East Branch Au Gres River',
    region: 'Northeast Lower Michigan',
    regionCode: 'NLP',
    notes: 'Arenac/Iosco County tributary. Cold upper sections with brown trout.',
    species: ['brown', 'brook'],
    type: 'freestone',
    tier: 2,
    access: 'East Andrews Road crossing near Alabaster area',
    regulations: 'General trout regulations.',
    gearType: 'general',
    primaryGauge: '04138030',
    gauges: [
      { id: '04138030', name: 'East Branch Au Gres River near Alabaster' },
    ],
  },

  // ── Southern / Central Lower Peninsula additions ──

  {
    id: 'dowagiac-river',
    name: 'Dowagiac River',
    region: 'Southwest Lower Michigan',
    regionCode: 'WLP',
    notes: 'Cass County spring creek with wild brown trout. One of southern Michigan\'s best trout streams. Cold, clear, spring-fed year-round.',
    species: ['brown'],
    type: 'spring_creek',
    tier: 1,
    access: 'State Highway 51 crossing, Dowagiac area, Sumnerville.',
    regulations: 'Type 2 water in sections. Check FO-200.',
    gearType: 'general',
    primaryGauge: '04101535',
    gauges: [
      { id: '04101535', name: 'Dowagiac River at State Hwy 51' },
      { id: '04101800', name: 'Dowagiac River at Sumnerville' },
      { id: '04101590', name: 'Dowagiac Creek near Dowagiac' },
    ],
  },
  {
    id: 'augusta-creek',
    name: 'Augusta Creek',
    region: 'Southwest Lower Michigan',
    regionCode: 'WLP',
    notes: 'Kalamazoo County spring creek near Augusta. Wild brown trout. Cold, clear, and surprisingly productive.',
    species: ['brown'],
    type: 'spring_creek',
    tier: 2,
    access: 'Near Augusta, county road crossings',
    regulations: 'General trout regulations.',
    gearType: 'general',
    primaryGauge: '04105700',
    gauges: [
      { id: '04105700', name: 'Augusta Creek near Augusta' },
    ],
  },
  {
    id: 'black-river-bangor',
    name: 'Black River (South Haven)',
    region: 'Southwest Lower Michigan',
    regionCode: 'WLP',
    notes: 'Van Buren County river. Steelhead and salmon runs from Lake Michigan. Some resident brown trout.',
    species: ['brown', 'steelhead'],
    type: 'freestone',
    tier: 2,
    access: 'Bangor area, South Haven area bridge crossings',
    regulations: 'General trout regulations. Lake Michigan tributary.',
    gearType: 'general',
    primaryGauge: '04102700',
    gauges: [
      { id: '04102700', name: 'South Branch Black River near Bangor' },
      { id: '04102776', name: 'Middle Branch Black River near South Haven' },
    ],
  },
  {
    id: 'red-cedar-river',
    name: 'Red Cedar River',
    region: 'Central Lower Michigan',
    regionCode: 'CLP',
    notes: 'Grand River tributary through Williamston and East Lansing. Brown trout in cold upper sections.',
    species: ['brown'],
    type: 'freestone',
    tier: 2,
    access: 'Williamston area, East Lansing bridges, MSU campus area',
    regulations: 'General trout regulations in upper sections.',
    gearType: 'general',
    primaryGauge: '04111379',
    gauges: [
      { id: '04111379', name: 'Red Cedar River near Williamston' },
      { id: '04112500', name: 'Red Cedar River at East Lansing' },
    ],
  },
  {
    id: 'thornapple-caledonia',
    name: 'Thornapple River (Lower)',
    region: 'West-Central Lower Michigan',
    regionCode: 'WLP',
    notes: 'Lower Thornapple near Caledonia. Brown trout in cooler sections.',
    species: ['brown'],
    type: 'freestone',
    tier: 2,
    access: 'Caledonia area bridge crossings',
    regulations: 'General trout regulations.',
    gearType: 'general',
    primaryGauge: '04118000',
    gauges: [
      { id: '04118000', name: 'Thornapple River near Caledonia' },
    ],
  },
  {
    id: 'chippewa-river-mp',
    name: 'Chippewa River',
    region: 'Central Lower Michigan',
    regionCode: 'CLP',
    notes: 'Mecosta/Isabella/Midland County river. Brown trout in cooler sections near Mt. Pleasant.',
    species: ['brown'],
    type: 'freestone',
    tier: 2,
    access: 'Mt. Pleasant area, Drew Road, S Homer Road crossings',
    regulations: 'General trout regulations.',
    gearType: 'general',
    primaryGauge: '04154000',
    gauges: [
      { id: '04154000', name: 'Chippewa River near Mt. Pleasant' },
      { id: '04153725', name: 'Chippewa River at Drew Rd' },
      { id: '04154512', name: 'Chippewa River at S Homer Rd near Midland' },
      { id: '04153905', name: 'N Branch Chippewa near Mt. Pleasant' },
    ],
  },
  {
    id: 'wolf-creek',
    name: 'Wolf Creek',
    region: 'Central Lower Michigan',
    regionCode: 'CLP',
    notes: 'Small Montcalm County stream near Vestaburg. Brown trout. Lightly fished.',
    species: ['brown'],
    type: 'freestone',
    tier: 3,
    access: 'Pine Grove Road crossing near Vestaburg',
    regulations: 'General trout regulations.',
    gearType: 'general',
    primaryGauge: '04154612',
    gauges: [
      { id: '04154612', name: 'Wolf Creek near Vestaburg' },
    ],
  },
  {
    id: 'pigeon-river-olive',
    name: 'Pigeon River (Ottawa County)',
    region: 'West-Central Lower Michigan',
    regionCode: 'WLP',
    notes: 'Ottawa County stream near Olive Center. Steelhead and resident trout. Not the Pigeon near Vanderbilt.',
    species: ['steelhead', 'brown'],
    type: 'freestone',
    tier: 2,
    access: '120th Avenue crossing near Olive Center',
    regulations: 'General trout regulations. Lake Michigan tributary.',
    gearType: 'general',
    primaryGauge: '04108862',
    gauges: [
      { id: '04108862', name: 'Pigeon River near Olive Center' },
    ],
  },
  {
    id: 'tittabawassee-river',
    name: 'Tittabawassee River',
    region: 'Central Lower Michigan',
    regionCode: 'CLP',
    notes: 'Major Saginaw tributary. Some brown trout in cold upper sections near Sanford.',
    species: ['brown'],
    type: 'freestone',
    tier: 2,
    access: 'Sanford area, Midland County road crossings',
    regulations: 'General trout regulations in designated sections.',
    gearType: 'general',
    primaryGauge: '04153300',
    gauges: [
      { id: '04153300', name: 'Tittabawassee River at Sanford' },
    ],
  },
];

// All unique gauge IDs across all rivers
export const ALL_GAUGE_IDS = [...new Set(
  RIVERS.flatMap(r => r.gauges.map(g => g.id))
)];

// All tributaries across all rivers, with parent reference
export const ALL_TRIBUTARIES = RIVERS.flatMap(r =>
  (r.tributaries || []).map(t => ({
    ...t,
    parentId: r.id,
    parentName: r.name,
    parentGauge: r.primaryGauge,
    region: r.region,
    regionCode: r.regionCode,
  }))
);

// Get tributaries for a specific river
export function getTributaries(riverId) {
  const river = RIVERS.find(r => r.id === riverId);
  return river?.tributaries || [];
}

// Helper: get rivers by region
export function getRiversByRegion(regionCode) {
  return RIVERS.filter(r => r.regionCode === regionCode);
}

// Helper: get rivers by species
export function getRiversBySpecies(species) {
  return RIVERS.filter(r => r.species.includes(species));
}

// Region metadata
export const REGIONS = {
  UP:  { label: 'Upper Peninsula',        abbr: 'UP',  color: '#2e5f3c' },
  NLP: { label: 'Northern Lower Michigan', abbr: 'NLP', color: '#1a3a5c' },
  WLP: { label: 'Western Lower Michigan',  abbr: 'WLP', color: '#5c3a1a' },
  CLP: { label: 'Central Lower Michigan',  abbr: 'CLP', color: '#5c1a3a' },
};